### PR TITLE
B1

### PR DESCRIPTION
**Pull request by razvaniuoras**
Hello i have added commit 1 b1 git2

### CODE REVIEW

**Comment by iuorasrazvan** [comment]
add a new line and i will merge.

**Comment by razvaniuoras** [comment]
added new line as you have requested. anything else

**Comment by iuorasrazvan** [comment]
Hello, i have merged.

**Comment by iuorasrazvan** [comment]
I wait new proposals for #1.

**Comment by iuorasrazvan** [comment]
Also for https://github.com/iuorasrazvan/edu/branches.

**Comment by iuorasrazvan** [comment]
https://github.com/iuorasrazvan/edu

**Comment by iuorasrazvan** [comment]
[x] email me
[] call me 
[] skype me.

**Comment by iuorasrazvan** [comment]
- [x] email me
- [ ] call me

**Pull request merged**
